[program:attendance-auto-sync]
command=/usr/bin/php /home/dev/biometric-system/artisan attendance:auto-sync:daemon --sleep=1
directory=/home/dev/biometric-system
autostart=true
autorestart=true
startsecs=3
stopasgroup=true
killasgroup=true
user=dev
stdout_logfile=/home/dev/biometric-system/storage/logs/attendance-auto-sync.log
stderr_logfile=/home/dev/biometric-system/storage/logs/attendance-auto-sync-error.log
